languageCode = "en-us"
title = "sr erisso"
baseurl = "http://www.erisso.com/"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
canonifyURLs = true

themesDir = "themes"
theme = "landing-page-hugo"
googleAnalytics = "UA-90848183-1"

# Params del theme hugo-project-page
[params]
description = "Building websites the easy way"

first_color="#f8f8f8"
first_border_color="#e7e7e7"
first_text_color="#333"

second_color="white"
second_text_color="#333"

header_color="#f8f8f8"
header_text_color="rgb(51, 51, 51)"

header_link_color="#777"
header_link_hover_color="rgb(51, 51, 51)"

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:works@erisso.com"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/sr_erisso"
[[params.social]]
    title = "github"
    icon = "github"
    url = "https://github.com/srerisso"
[[params.social]]
    title = "linkedin"
    icon = "linkedin"
    url = "http://linkedin.com/in/yourusername"